org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

neoForge.parchment.minecraftVersion=1.21.10
neoForge.parchment.mappingsVersion=2025.10.12

# Mod Info
undergarden_version=0.9.7
mod_id=undergarden

# Minecraft
minecraft_version=26.1.2

# NeoForge
neo_version=26.1.2.71

# Deps
emi_version=1.1.22+1.21.1
jei_version=29.6.2.31
jade_version=8251883
better_advancements_version=5850587

create_version=6.0.6-98
ponder_version=1.0.56
flywheel_version=1.0.4