org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

neoForge.parchment.minecraftVersion=1.21.10
neoForge.parchment.mappingsVersion=2025.10.12

# Mod Info
undergarden_version=0.9.5
mod_id=undergarden

# Minecraft
minecraft_version=26.1

# NeoForge
neo_version=26.1.0.1-beta

# Deps
emi_version=1.1.22+1.21.1
jei_version=19.27.0.340
jade_version=7545219
better_advancements_version=5850587

create_version=6.0.6-98
ponder_version=1.0.56
flywheel_version=1.0.4